### PR TITLE
Support for Raspberry Pi 2 and 3

### PR DESCRIPTION
**Pull request by vimalvnair**
Inspired from https://github.com/Ginkgo23/PiFmRPi2

### CODE REVIEW

**Comment by bskari** [comment]
Awesome, thank you so much! I'm going to take a look at this tonight. I have a Pi B and a Zero that I can test this on, but my Pi 2 recently failed and I haven't gotten a Pi 3 yet. I'm hoping I can find somebody tonight who has one. Have you tested this with an RC car with different Pis?

**Comment by vimalvnair** [comment]
I tested it in Pi B and Pi 3 using an RC car. It works fine.

**Comment by vimalvnair** [comment]
@bskari Did you get a chance to look at this?

**Comment by bskari** [comment]
Awesome, this looks great, I just tested it out. Thank you so much, I really appreciate it!

**Comment by vimalvnair** [comment]
You are welcome. I am glad I could help. :)

**Pull request merged**
